import { LocationKey } from '../types';
import { buildSearchUrls } from '../utils/helpers';

// ─── SDE / SWE / SE Jobs ──────────────────────────────────────────────────────
export function getSdeJobs(location: LocationKey) {
  const JOBS = [
    { id:'s1',  title:'SDE-2 · Node.js Backend',         keyword:'SDE 2 Node.js backend',               roleType:'SDE' as const, interviewType:'Both DSA + SD' as const, dsaFocus:'Trees, Graphs, DP, Sliding Window',  sdFocus:'Leaderboard, Rate limiter, Job queue',    rounds:'1 OA + 2 DSA + 1 SD + 1 HR', ctc:'20-35 LPA', score:97, companies:[{name:'Scaler',apply:'https://www.scaler.com/careers/',loc:'Hyderabad'},{name:'Vyapar',apply:'https://vyapar.in/careers',loc:'Hyderabad'},{name:'Freshworks',apply:'https://careers.freshworks.com/',loc:'Hyderabad'},{name:'Postman',apply:'https://www.postman.com/company/careers/',loc:'Remote'},{name:'Darwinbox',apply:'https://darwinbox.com/careers',loc:'Hyderabad'}] },
    { id:'s2',  title:'SDE-2 · TypeScript Platform',      keyword:'SDE 2 TypeScript platform backend',    roleType:'SDE' as const, interviewType:'Both DSA + SD' as const, dsaFocus:'Arrays, Trees, Heaps, Binary Search', sdFocus:'Distributed cache, API design',           rounds:'1 OA + 2 DSA + 1 SD',        ctc:'20-32 LPA', score:95, companies:[{name:'Sprinto',apply:'https://sprinto.com/careers/',loc:'Remote'},{name:'BrowserStack',apply:'https://www.browserstack.com/careers',loc:'Remote'},{name:'Leadsquared',apply:'https://www.leadsquared.com/careers/',loc:'Hyderabad'},{name:'Zuddl',apply:'https://www.zuddl.com/careers',loc:'Remote'},{name:'HashedIn',apply:'https://hashedin.com/careers/',loc:'Hyderabad'}] },
    { id:'s3',  title:'Software Engineer II · Backend',   keyword:'Software Engineer 2 backend systems',  roleType:'SWE' as const, interviewType:'Both DSA + SD' as const, dsaFocus:'Graphs, DP, Binary Search, Trees',   sdFocus:'Microservices, Message queue',            rounds:'2 DSA + 1 SD + 1 HR',        ctc:'22-38 LPA', score:91, companies:[{name:'Razorpay',apply:'https://razorpay.com/jobs/',loc:'Hyderabad'},{name:'Groww',apply:'https://groww.in/about/careers',loc:'Remote'},{name:'PhonePe',apply:'https://careers.phonepe.com/',loc:'Hyderabad'},{name:'Meesho',apply:'https://careers.meesho.com/',loc:'Remote'},{name:'Swiggy',apply:'https://careers.swiggy.com/',loc:'Hyderabad'}] },
    { id:'s4',  title:'SE · Distributed Systems',         keyword:'Software Engineer distributed systems', roleType:'SE'  as const, interviewType:'System Design' as const, dsaFocus:'Graphs, Trees, Concurrency',         sdFocus:'Distributed lock, Consensus, CAP',        rounds:'1 DSA + 2 SD + 1 HR',        ctc:'25-40 LPA', score:88, companies:[{name:'BrowserStack',apply:'https://www.browserstack.com/careers',loc:'Remote'},{name:'Postman',apply:'https://www.postman.com/company/careers/',loc:'Remote'},{name:'Turing',apply:'https://www.turing.com/jobs',loc:'Remote US'},{name:'Arc.dev',apply:'https://arc.dev/remote-jobs?search=distributed',loc:'Remote'},{name:'Sigmoid',apply:'https://www.sigmoid.com/careers/',loc:'Hyderabad'}] },
    { id:'s5',  title:'SDE-2 · Redis / Caching Systems',  keyword:'SDE 2 Redis caching backend Node.js',  roleType:'SDE' as const, interviewType:'Both DSA + SD' as const, dsaFocus:'Heaps, Hash maps, Sorted Sets',       sdFocus:'Cache invalidation, Redis Sorted Sets',   rounds:'1 OA + 2 DSA + 1 SD',        ctc:'20-32 LPA', score:93, companies:[{name:'Scaler',apply:'https://www.scaler.com/careers/',loc:'Hyderabad'},{name:'Trackier',apply:'https://trackier.com/careers/',loc:'Hyderabad'},{name:'CloudSEK',apply:'https://cloudsek.com/careers',loc:'Hyderabad'},{name:'Swiggy',apply:'https://careers.swiggy.com/',loc:'Hyderabad'},{name:'PhonePe',apply:'https://careers.phonepe.com/',loc:'Hyderabad'}] },
    { id:'s6',  title:'SWE · Real-time / Event-driven',   keyword:'Software Engineer real-time Node.js',   roleType:'SWE' as const, interviewType:'Both DSA + SD' as const, dsaFocus:'Graphs, Trees, Sliding Window',       sdFocus:'Pub/Sub, WebSockets, Fan-out',            rounds:'1 DSA + 1 SD + 1 HR',        ctc:'20-30 LPA', score:86, companies:[{name:'Zuddl',apply:'https://www.zuddl.com/careers',loc:'Remote'},{name:'Swiggy',apply:'https://careers.swiggy.com/',loc:'Hyderabad'},{name:'Freshworks',apply:'https://careers.freshworks.com/',loc:'Hyderabad'},{name:'Leadsquared',apply:'https://www.leadsquared.com/careers/',loc:'Hyderabad'},{name:'Eka Software',apply:'https://www.ekasoftware.com/careers/',loc:'Hyderabad'}] },
    { id:'s7',  title:'SDE-2 · BullMQ / Worker Autoscaling', keyword:'SDE job queue BullMQ worker Node.js',roleType:'SDE' as const, interviewType:'Both DSA + SD' as const, dsaFocus:'Heaps, Graphs, Priority Queue',       sdFocus:'Distributed job queue, EC2 ASG',          rounds:'1 OA + 2 DSA + 1 SD',        ctc:'20-30 LPA', score:94, companies:[{name:'Scaler',apply:'https://www.scaler.com/careers/',loc:'Hyderabad'},{name:'Swiggy',apply:'https://careers.swiggy.com/',loc:'Hyderabad'},{name:'Freshworks',apply:'https://careers.freshworks.com/',loc:'Hyderabad'},{name:'PhonePe',apply:'https://careers.phonepe.com/',loc:'Hyderabad'},{name:'Trackier',apply:'https://trackier.com/careers/',loc:'Hyderabad'}] },
    { id:'s8',  title:'SDE-2 · AWS Cloud Backend',        keyword:'SDE 2 AWS cloud backend Node.js',      roleType:'SDE' as const, interviewType:'Both DSA + SD' as const, dsaFocus:'Graphs, DP, Stack, Trees',            sdFocus:'Lambda, EC2 ASG, CloudWatch',             rounds:'1 OA + 2 DSA + 1 SD + 1 HR', ctc:'22-35 LPA', score:90, companies:[{name:'Darwinbox',apply:'https://darwinbox.com/careers',loc:'Hyderabad'},{name:'BrowserStack',apply:'https://www.browserstack.com/careers',loc:'Remote'},{name:'HashedIn',apply:'https://hashedin.com/careers/',loc:'Hyderabad'},{name:'Turing',apply:'https://www.turing.com/jobs',loc:'Remote US'},{name:'Groww',apply:'https://groww.in/about/careers',loc:'Remote'}] },
    { id:'s9',  title:'SE II · Fintech Backend',          keyword:'Software Engineer fintech backend',     roleType:'SE'  as const, interviewType:'Both DSA + SD' as const, dsaFocus:'DP, Trees, Two Pointers, Heaps',      sdFocus:'Payment system, Idempotency, Saga',       rounds:'2 DSA + 1 SD + 1 HR',        ctc:'24-38 LPA', score:85, companies:[{name:'Razorpay',apply:'https://razorpay.com/jobs/',loc:'Hyderabad'},{name:'Slice',apply:'https://www.sliceit.com/careers',loc:'Hyderabad'},{name:'PhonePe',apply:'https://careers.phonepe.com/',loc:'Hyderabad'},{name:'Groww',apply:'https://groww.in/about/careers',loc:'Remote'},{name:'Zepto',apply:'https://www.zeptonow.com/careers',loc:'Hyderabad'}] },
    { id:'s10', title:'SWE · API Platform Engineering',   keyword:'Software Engineer API platform Node.js',roleType:'SWE' as const, interviewType:'Both DSA + SD' as const, dsaFocus:'Trees, Tries, Two Pointers',          sdFocus:'Rate limiter, API gateway, JWT/OAuth2',   rounds:'1 OA + 2 DSA + 1 SD',        ctc:'22-34 LPA', score:91, companies:[{name:'Postman',apply:'https://www.postman.com/company/careers/',loc:'Remote'},{name:'Sprinto',apply:'https://sprinto.com/careers/',loc:'Remote'},{name:'CloudSEK',apply:'https://cloudsek.com/careers',loc:'Hyderabad'},{name:'Leadsquared',apply:'https://www.leadsquared.com/careers/',loc:'Hyderabad'},{name:'Darwinbox',apply:'https://darwinbox.com/careers',loc:'Hyderabad'}] },
    { id:'s11', title:'SE · Microservices Architecture',  keyword:'Software Engineer microservices Docker', roleType:'SE'  as const, interviewType:'Mostly SD'     as const, dsaFocus:'Graphs, Trees, Concurrency',         sdFocus:'Service mesh, Event-driven, CQRS',        rounds:'1 DSA + 2 SD + 1 HR',        ctc:'22-36 LPA', score:87, companies:[{name:'Meesho',apply:'https://careers.meesho.com/',loc:'Remote'},{name:'Zepto',apply:'https://www.zeptonow.com/careers',loc:'Hyderabad'},{name:'Swiggy',apply:'https://careers.swiggy.com/',loc:'Hyderabad'},{name:'BrowserStack',apply:'https://www.browserstack.com/careers',loc:'Remote'},{name:'Turing',apply:'https://www.turing.com/jobs',loc:'Remote US'}] },
    { id:'s12', title:'SDE-2 · Backend Infra & Scale',    keyword:'SDE 2 backend infrastructure scaling',  roleType:'SDE' as const, interviewType:'Mostly SD'     as const, dsaFocus:'Heaps, Graphs, Consistent Hashing',   sdFocus:'Autoscaling, CDN, DB sharding',           rounds:'1 DSA + 2 SD + 1 HR',        ctc:'24-40 LPA', score:89, companies:[{name:'Razorpay',apply:'https://razorpay.com/jobs/',loc:'Hyderabad'},{name:'PhonePe',apply:'https://careers.phonepe.com/',loc:'Hyderabad'},{name:'Groww',apply:'https://groww.in/about/careers',loc:'Remote'},{name:'Arc.dev',apply:'https://arc.dev/remote-jobs?search=backend',loc:'Remote'},{name:'Freshworks',apply:'https://careers.freshworks.com/',loc:'Hyderabad'}] },
  ];
  return JOBS.map(j => ({ ...j, searchUrls: buildSearchUrls(j.keyword, location) }));
}

// ─── Resume-matched Jobs ──────────────────────────────────────────────────────
export function getResumeJobs(location: LocationKey) {
  const JOBS = [
    { id:'r1',  title:'Node.js Backend Engineer',          keyword:'Node.js backend engineer',             stackFocus:'Node.js + Express.js', skills:['Node.js','Express.js','TypeScript','MongoDB'],           score:96, ctc:'16-28 LPA', companies:[{name:'Scaler',apply:'https://www.scaler.com/careers/',loc:'Hyderabad'},{name:'Leadsquared',apply:'https://www.leadsquared.com/careers/',loc:'Hyderabad'},{name:'Instahyre',apply:'https://www.instahyre.com/',loc:'Hyderabad'},{name:'Trackier',apply:'https://trackier.com/careers/',loc:'Hyderabad'},{name:'Freshworks',apply:'https://careers.freshworks.com/',loc:'Hyderabad'}] },
    { id:'r2',  title:'MEAN Stack Developer',              keyword:'MEAN stack developer Angular Node.js',  stackFocus:'MEAN Stack full',      skills:['MongoDB','Express.js','Angular','Node.js','TypeScript'],   score:94, ctc:'14-24 LPA', companies:[{name:'Vyapar',apply:'https://vyapar.in/careers',loc:'Hyderabad'},{name:'Darwinbox',apply:'https://darwinbox.com/careers',loc:'Hyderabad'},{name:'HashedIn',apply:'https://hashedin.com/careers/',loc:'Hyderabad'},{name:'Eka Software',apply:'https://www.ekasoftware.com/careers/',loc:'Hyderabad'},{name:'Zuddl',apply:'https://www.zuddl.com/careers',loc:'Remote'}] },
    { id:'r3',  title:'Node.js + Redis Engineer',          keyword:'Node.js Redis engineer caching backend', stackFocus:'Node.js + Redis + BullMQ', skills:['Node.js','Redis','TypeScript','BullMQ','MongoDB'],   score:95, ctc:'18-28 LPA', companies:[{name:'Scaler',apply:'https://www.scaler.com/careers/',loc:'Hyderabad'},{name:'Trackier',apply:'https://trackier.com/careers/',loc:'Hyderabad'},{name:'CloudSEK',apply:'https://cloudsek.com/careers',loc:'Hyderabad'},{name:'Swiggy',apply:'https://careers.swiggy.com/',loc:'Hyderabad'},{name:'PhonePe',apply:'https://careers.phonepe.com/',loc:'Hyderabad'}] },
    { id:'r4',  title:'Microservices Engineer · Node.js',  keyword:'microservices Node.js Docker engineer',  stackFocus:'Microservices + Docker', skills:['Node.js','Microservices','Docker','Redis','AWS'],        score:92, ctc:'20-32 LPA', companies:[{name:'Meesho',apply:'https://careers.meesho.com/',loc:'Remote'},{name:'BrowserStack',apply:'https://www.browserstack.com/careers',loc:'Remote'},{name:'Zepto',apply:'https://www.zeptonow.com/careers',loc:'Hyderabad'},{name:'Razorpay',apply:'https://razorpay.com/jobs/',loc:'Hyderabad'},{name:'Swiggy',apply:'https://careers.swiggy.com/',loc:'Hyderabad'}] },
    { id:'r5',  title:'Full Stack · Angular + Node.js',    keyword:'Angular Node.js full stack MEAN',        stackFocus:'Angular + Node.js',    skills:['Angular','Node.js','TypeScript','MongoDB','Express.js'],  score:90, ctc:'14-24 LPA', companies:[{name:'Darwinbox',apply:'https://darwinbox.com/careers',loc:'Hyderabad'},{name:'Vyapar',apply:'https://vyapar.in/careers',loc:'Hyderabad'},{name:'HashedIn',apply:'https://hashedin.com/careers/',loc:'Hyderabad'},{name:'Leadsquared',apply:'https://www.leadsquared.com/careers/',loc:'Hyderabad'},{name:'Freshworks',apply:'https://careers.freshworks.com/',loc:'Hyderabad'}] },
    { id:'r6',  title:'Node.js Engineer · AWS Cloud',      keyword:'Node.js AWS engineer cloud backend',     stackFocus:'Node.js + AWS',        skills:['Node.js','AWS','TypeScript','Docker','PostgreSQL'],         score:91, ctc:'18-30 LPA', companies:[{name:'Sigmoid',apply:'https://www.sigmoid.com/careers/',loc:'Hyderabad'},{name:'HashedIn',apply:'https://hashedin.com/careers/',loc:'Hyderabad'},{name:'BrowserStack',apply:'https://www.browserstack.com/careers',loc:'Remote'},{name:'Turing',apply:'https://www.turing.com/jobs',loc:'Remote US'},{name:'Arc.dev',apply:'https://arc.dev/remote-jobs?search=Node.js',loc:'Remote'}] },
    { id:'r7',  title:'Node.js + MongoDB Developer',       keyword:'Node.js MongoDB developer backend',      stackFocus:'Node.js + MongoDB',    skills:['Node.js','MongoDB','Express.js','TypeScript','Redis'],     score:93, ctc:'14-24 LPA', companies:[{name:'Instahyre',apply:'https://www.instahyre.com/',loc:'Hyderabad'},{name:'Leadsquared',apply:'https://www.leadsquared.com/careers/',loc:'Hyderabad'},{name:'CloudSEK',apply:'https://cloudsek.com/careers',loc:'Hyderabad'},{name:'Vyapar',apply:'https://vyapar.in/careers',loc:'Hyderabad'},{name:'Zuddl',apply:'https://www.zuddl.com/careers',loc:'Remote'}] },
    { id:'r8',  title:'Node.js · BullMQ / Job Queues',     keyword:'Node.js BullMQ job queue Redis worker',  stackFocus:'BullMQ + Redis',       skills:['Node.js','BullMQ','Redis','TypeScript','AWS'],            score:92, ctc:'18-28 LPA', companies:[{name:'Scaler',apply:'https://www.scaler.com/careers/',loc:'Hyderabad'},{name:'Swiggy',apply:'https://careers.swiggy.com/',loc:'Hyderabad'},{name:'Freshworks',apply:'https://careers.freshworks.com/',loc:'Hyderabad'},{name:'Trackier',apply:'https://trackier.com/careers/',loc:'Hyderabad'},{name:'PhonePe',apply:'https://careers.phonepe.com/',loc:'Hyderabad'}] },
    { id:'r9',  title:'Senior Node.js TypeScript Engineer', keyword:'senior Node.js TypeScript backend',     stackFocus:'Node.js + TypeScript', skills:['Node.js','TypeScript','MongoDB','Redis','AWS'],            score:91, ctc:'20-32 LPA', companies:[{name:'Postman',apply:'https://www.postman.com/company/careers/',loc:'Remote'},{name:'BrowserStack',apply:'https://www.browserstack.com/careers',loc:'Remote'},{name:'Sprinto',apply:'https://sprinto.com/careers/',loc:'Remote'},{name:'Turing',apply:'https://www.turing.com/jobs',loc:'Remote US'},{name:'Groww',apply:'https://groww.in/about/careers',loc:'Remote'}] },
    { id:'r10', title:'Node.js + PostgreSQL Engineer',     keyword:'Node.js PostgreSQL backend TypeScript',  stackFocus:'Node.js + PostgreSQL', skills:['Node.js','PostgreSQL','TypeScript','Redis','JWT'],         score:89, ctc:'16-26 LPA', companies:[{name:'Slice',apply:'https://www.sliceit.com/careers',loc:'Hyderabad'},{name:'Razorpay',apply:'https://razorpay.com/jobs/',loc:'Hyderabad'},{name:'Groww',apply:'https://groww.in/about/careers',loc:'Remote'},{name:'Darwinbox',apply:'https://darwinbox.com/careers',loc:'Hyderabad'},{name:'Leadsquared',apply:'https://www.leadsquared.com/careers/',loc:'Hyderabad'}] },
    { id:'r11', title:'MERN Stack Developer',              keyword:'MERN stack React Node.js MongoDB',       stackFocus:'MERN Stack',           skills:['MongoDB','Express.js','React','Node.js','TypeScript'],     score:88, ctc:'14-26 LPA', companies:[{name:'HashedIn',apply:'https://hashedin.com/careers/',loc:'Hyderabad'},{name:'Zuddl',apply:'https://www.zuddl.com/careers',loc:'Remote'},{name:'Instahyre',apply:'https://www.instahyre.com/',loc:'Hyderabad'},{name:'Sigmoid',apply:'https://www.sigmoid.com/careers/',loc:'Hyderabad'},{name:'Eka Software',apply:'https://www.ekasoftware.com/careers/',loc:'Hyderabad'}] },
    { id:'r12', title:'Node.js Auth API · JWT/OAuth2',     keyword:'Node.js JWT OAuth2 API security',        stackFocus:'Node.js + Auth/Security', skills:['Node.js','JWT','OAuth2','TypeScript','Redis'],          score:87, ctc:'14-24 LPA', companies:[{name:'Sprinto',apply:'https://sprinto.com/careers/',loc:'Remote'},{name:'CloudSEK',apply:'https://cloudsek.com/careers',loc:'Hyderabad'},{name:'Darwinbox',apply:'https://darwinbox.com/careers',loc:'Hyderabad'},{name:'Freshworks',apply:'https://careers.freshworks.com/',loc:'Hyderabad'},{name:'HashedIn',apply:'https://hashedin.com/careers/',loc:'Hyderabad'}] },
  ];
  return JOBS.map(j => ({ ...j, searchUrls: buildSearchUrls(j.keyword, location) }));
}

// ─── Teaching Opportunities ───────────────────────────────────────────────────
export function getTeachingOpportunities() {
  return [
    { id:'t1', title:'Codementor — DSA & Backend Mentor',  platform:'Codementor',       audience:'Professionals worldwide',    earn:'$15–$120/hr',          languages:['Python','Java','C++','Node.js','DSA','System Design'], details:'#1 platform for 1-on-1 coding mentorship. SDE interview prep mentors booked 3-4 weeks out. Your Redis/BullMQ/distributed-systems experience is rare content.', howToStart:'Apply → set DSA/Node.js/System Design tags → set hourly rate → get matched. Verified badge increases bookings 3x.', demand:'Very High', score:95, portals:[{name:'Apply as Mentor',url:'https://www.codementor.io/mentor/apply',type:'Register'},{name:'DSA Mentors',url:'https://www.codementor.io/mentors/data-structures',type:'Research'}] },
    { id:'t2', title:'Chegg Tutors — CS/Programming',      platform:'Chegg',            audience:'US/Canada college students', earn:'$20–$40/hr',           languages:['Python','Java','C++','DSA','Algorithms'],           details:'Largest US student platform. Thousands of daily CS requests. Consistent volume. Great for building USD income alongside your main job.', howToStart:'Apply → select CS subjects → background check → start taking requests.', demand:'Very High', score:88, portals:[{name:'Become a Tutor',url:'https://www.chegg.com/tutors/become-a-tutor/',type:'Register'}] },
    { id:'t3', title:'Wyzant — CS Tutor (US Market)',      platform:'Wyzant',           audience:'US college students',        earn:'$40–$100/hr',          languages:['Python','Java','C++','DSA','Web Dev'],              details:'Top US tutoring marketplace. SDE-2 background makes you highly credible. USD payment via PayPal. Summer + exam seasons = 3x volume.', howToStart:'Create profile → set subjects + hourly rate → US students book via video sessions.', demand:'High', score:85, portals:[{name:'Teach on Wyzant',url:'https://www.wyzant.com/teach',type:'Register'}] },
    { id:'t4', title:'Udemy — DSA / Backend Course',       platform:'Udemy',            audience:'Global 150M+ learners',      earn:'₹50K–₹5L+/year passive', languages:['Python','Java','C++','Node.js','DSA','System Design'], details:'Create once, earn forever. Your contest infra + Redis Sorted Sets + BullMQ content is RARE — no one teaches this from production experience.', howToStart:'Plan 20-30 topics → record with OBS → upload → price ₹499-1499 → Udemy markets for you.', demand:'Extremely High', score:93, portals:[{name:'Start Teaching',url:'https://www.udemy.com/teaching/',type:'Register'},{name:'Instructor Guide',url:'https://teach.udemy.com/',type:'Guide'}] },
    { id:'t5', title:'Preply — Programming Tutor (Global)',platform:'Preply',           audience:'Students in 180+ countries', earn:'$10–$80/hr',           languages:['Python','Java','C++','JavaScript','DSA'],           details:'Global tutoring. High demand from career switchers in Europe/US. Preply takes 33% initially, reduces to 18% over time.', howToStart:'Profile + intro video → set rate → students discover and book.', demand:'High', score:82, portals:[{name:'Teach on Preply',url:'https://preply.com/en/teach',type:'Register'}] },
    { id:'t6', title:'Toptal — Expert Mentor Network',     platform:'Toptal',           audience:'Senior professionals worldwide', earn:'$60–$200/hr',       languages:['JavaScript','Node.js','DSA','System Design'],      details:'Top 3% network. Highest pay. 5-step rigorous screening. Your SDE-2 + distributed systems experience makes you competitive.', howToStart:'Apply → English → DSA screening → live coding → test project → 3-5 weeks.', demand:'High', score:90, portals:[{name:'Apply to Toptal',url:'https://www.toptal.com/freelance',type:'Register'}] },
    { id:'t7', title:'YouTube + Teachable — Own Brand',    platform:'YouTube+Teachable',audience:'Global, South Asian diaspora',earn:'₹2-20L/year scalable', languages:['Python','Java','Node.js','DSA','System Design'],    details:'Build your own DSA/backend brand. Telugu + English SDE prep has massive gap. Smart Interviews background = instant credibility. Sell premium courses ₹999-4999.', howToStart:'1 video/week → YouTube + LinkedIn → 1000 subs → launch ₹999 course on Teachable.', demand:'Extremely High', score:87, portals:[{name:'YouTube Studio',url:'https://studio.youtube.com/',type:'Platform'},{name:'Teachable',url:'https://teachable.com/',type:'Platform'},{name:'Gumroad',url:'https://gumroad.com/',type:'Platform'}] },
    { id:'t8', title:'Coursera/edX — Expert Instructor',  platform:'Coursera+edX',     audience:'Global millions',            earn:'Revenue share + brand', languages:['Any — Node.js/DSA/System Design'],                  details:'Partner with universities. "Distributed Systems with Node.js" or "DSA for SDE Interviews" would be unique industry-practitioner content with real metrics.', howToStart:'Submit course proposal → approved → build with their tools → royalties per enrolled learner.', demand:'High', score:80, portals:[{name:'Coursera Teach',url:'https://www.coursera.org/teach',type:'Register'},{name:'edX Partner',url:'https://www.edx.org/become-a-partner',type:'Register'}] },
  ];
}

// ─── Freelance Opportunities ──────────────────────────────────────────────────
export function getFreelanceOpportunities() {
  return [
    { id:'f1', title:'Upwork — Node.js / MEAN Stack',    platform:'Upwork',       clients:'US, UK, Australia, Europe',       earn:'$25–$80/hr or $500–$8K/project', stack:['Node.js','MongoDB','Angular','Express.js','TypeScript','Redis'],   demand:'Very High', score:96, details:'50,000+ active Node.js postings. SDE-2 background commands $40-80/hr. First 2-3 projects at lower rate to build reviews, then raise steadily.', howToStart:'Profile → "Node.js + Redis + Distributed Systems SDE-2" headline → bid 5-10 jobs/day → win first at competitive rate.', hotProjects:['REST API development','MEAN stack dashboard','Real-time Socket.io app','Redis caching layer','Microservices backend'], portals:[{name:'Node.js Jobs',url:'https://www.upwork.com/freelance-jobs/applying/?q=Node.js+backend',type:'Jobs'},{name:'MEAN Stack Jobs',url:'https://www.upwork.com/freelance-jobs/applying/?q=MEAN+stack',type:'Jobs'},{name:'Create Profile',url:'https://www.upwork.com/freelancer/signup/',type:'Register'}] },
    { id:'f2', title:'Turing.com — Remote SDE (US)',     platform:'Turing',       clients:'Top US tech companies',           earn:'$40–$80/hr (~₹80K–₹1.5L/mo)',   stack:['Node.js','TypeScript','React','Microservices','AWS','PostgreSQL'], demand:'Very High', score:93, details:'No bidding — matched like an employee. Node.js developers placed within 2-4 weeks. Long-term stable remote income from US companies.', howToStart:'Apply → AI assessment → DSA test → live coding → matched with US company within 2-4 weeks.', hotProjects:['Full-time remote SDE role','Backend platform work','API development','Microservices'], portals:[{name:'Apply to Turing',url:'https://www.turing.com/jobs',type:'Register'},{name:'Turing Assessment',url:'https://developers.turing.com/',type:'Register'}] },
    { id:'f3', title:'Toptal — Elite MEAN Developer',    platform:'Toptal',       clients:'Fortune 500 + top startups',      earn:'$60–$150/hr guaranteed',         stack:['Node.js','React','Angular','TypeScript','System Design','AWS'],   demand:'High', score:92, details:'Top 3% network. Airbnb/Zendesk-level clients. Highest freelance rates globally. 5-step screening.', howToStart:'Apply → English → algorithm screening → live coding → test project → culture fit → 2-4 weeks.', hotProjects:['Backend API architecture','Full stack MEAN/MERN','Technical consulting','Code review'], portals:[{name:'Apply to Toptal',url:'https://www.toptal.com/freelance',type:'Register'},{name:'Node.js Network',url:'https://www.toptal.com/nodejs',type:'Research'}] },
    { id:'f4', title:'Arc.dev — Remote MEAN Developer',  platform:'Arc.dev',      clients:'US & EU remote-first startups',   earn:'$45–$100/hr',                    stack:['Node.js','React','Angular','TypeScript','AWS','MongoDB'],         demand:'High', score:90, details:'Pre-vetted network. Less competitive than Toptal. Fast matching 1-2 weeks after acceptance. Node.js + TypeScript in premium demand.', howToStart:'Apply → screening → accepted to marketplace → clients find you or apply to active postings.', hotProjects:['Startup MVP backend','Full stack MEAN/MERN','API architecture','Tech consulting'], portals:[{name:'Apply to Arc.dev',url:'https://arc.dev/developer/apply',type:'Register'},{name:'Node.js Remote',url:'https://arc.dev/remote-jobs?search=Node.js',type:'Jobs'}] },
    { id:'f5', title:'Freelancer.com — MEAN/MERN',       platform:'Freelancer.com',clients:'Global SMBs, early startups',    earn:'$15–$60/hr or ₹20K–₹2L/project', stack:['Node.js','Angular','React','MongoDB','Express.js','TypeScript'],   demand:'High', score:85, details:'Good for early portfolio building. Thousands of MEAN/MERN projects daily. Less competitive barrier than Toptal/Upwork.', howToStart:'Profile → bid 10-15 small projects → win 2-3 → build reviews → increase rates.', hotProjects:['E-commerce Node.js backend','Angular admin dashboard','REST API integration','MongoDB setup'], portals:[{name:'Node.js Projects',url:'https://www.freelancer.com/jobs/?keyword=Node.js+backend',type:'Jobs'},{name:'MEAN Stack Jobs',url:'https://www.freelancer.com/jobs/?keyword=MEAN+stack',type:'Jobs'},{name:'Sign Up',url:'https://www.freelancer.com/signup',type:'Register'}] },
    { id:'f6', title:'Guru.com — Backend Contracts',     platform:'Guru.com',     clients:'US, UK, Canada businesses',       earn:'$20–$70/hr',                     stack:['Node.js','TypeScript','MongoDB','PostgreSQL','Docker','Express.js'],demand:'Medium-High', score:82, details:'Long-term engagements. Less competitive than Upwork. ₹2-8L/month contracts common. WorkRooms for client relationships.', howToStart:'Portfolio → verified skills → personalized proposals → long-term client relationships.', hotProjects:['Backend API development','DB design','Node.js REST backend','AWS deployment'], portals:[{name:'Node.js Jobs',url:'https://www.guru.com/d/jobs/q/node-js/',type:'Jobs'},{name:'Sign Up',url:'https://www.guru.com/users/signup.aspx',type:'Register'}] },
    { id:'f7', title:'Fiverr Pro — MEAN/MERN Gigs',      platform:'Fiverr Pro',   clients:'Global SMBs, solopreneurs',       earn:'$100–$3,000/gig',                stack:['Node.js','Angular','React','MongoDB','Express.js','TypeScript'],   demand:'High', score:84, details:'Service packages: "MEAN stack app — $400", "Node.js REST API — $250". Fiverr Pro badge = 3x more visibility and premium client access.', howToStart:'Apply for Pro → 3-5 specific gigs with 3-tier pricing → portfolio screenshots → promote on LinkedIn.', hotProjects:['MEAN/MERN web app','REST API','Angular dashboard','MongoDB migration'], portals:[{name:'Fiverr Pro',url:'https://www.fiverr.com/pro',type:'Register'},{name:'MEAN Stack Gigs',url:'https://www.fiverr.com/search/gigs?query=MEAN+stack',type:'Research'}] },
    { id:'f8', title:'PeoplePerHour — UK/EU Projects',   platform:'PeoplePerHour',clients:'UK, EU businesses',               earn:'£25–£75/hr (~₹2,600–₹8,000/hr)', stack:['Node.js','Express.js','MongoDB','TypeScript','Angular','REST APIs'],demand:'Medium-High', score:80, details:'UK/EU focused. Less competition. UK SMBs value quality over lowest price. Good for building long-term international client base.', howToStart:'Profile → Hourlies (packages) → bid projects → respond fast to UK timezone (evening India time).', hotProjects:['Node.js API','Angular web app','E-commerce backend','REST APIs'], portals:[{name:'Browse Projects',url:'https://www.peopleperhour.com/freelance-node.js-jobs',type:'Jobs'},{name:'Sign Up',url:'https://www.peopleperhour.com/signup',type:'Register'}] },
  ];
}
